/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 21 09:58:29 GMT 2023
 */

package org.apache.commons.io;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class FileCleaner_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.io.FileCleaner"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/antonio/Documents/GitHub/commons-io"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/nm/9k1qd0l12h9_56_0pzt237qc0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(FileCleaner_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.io.FileCleaningTracker",
      "org.apache.commons.io.FileCleaningTracker$Reaper",
      "org.apache.commons.io.FileDeleteStrategy",
      "org.apache.commons.io.FileDeleteStrategy$ForceFileDeleteStrategy",
      "org.apache.commons.io.FileCleaner"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(FileCleaner_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.io.FileCleaningTracker",
      "org.apache.commons.io.FileCleaner",
      "org.apache.commons.io.FileDeleteStrategy$ForceFileDeleteStrategy",
      "org.apache.commons.io.FileDeleteStrategy",
      "org.apache.commons.io.FileCleaningTracker$Reaper",
      "org.apache.commons.io.FileCleaningTracker$Tracker",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.input.Tailer",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.build.AbstractOriginSupplier",
      "org.apache.commons.io.build.AbstractStreamBuilder",
      "org.apache.commons.io.input.Tailer$Builder",
      "org.apache.commons.io.input.TailerListenerAdapter",
      "org.apache.commons.io.Charsets",
      "org.apache.commons.io.build.AbstractOrigin",
      "org.apache.commons.io.build.AbstractOrigin$PathOrigin",
      "org.apache.commons.io.input.Tailer$TailablePath",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.DeletingPathVisitor",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.io.build.AbstractOrigin$WriterOrigin",
      "org.apache.commons.io.build.AbstractOrigin$ReaderOrigin",
      "org.apache.commons.io.build.AbstractOrigin$InputStreamOrigin",
      "org.apache.commons.io.build.AbstractOrigin$FileOrigin"
    );
  }
}
